<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <?php foreach ($params['buildingTypes'] as $buildingType) : ?>
          <div class="row mb-4 border-bottom border-dark">
            <div class="d-flex">
              <div class="desc pl-3">
                <div class="d-flex text align-items-center">
                  <h3><span><?= $buildingType['ingatlanTipus'] ?></span></h3>
                </div>
              </div>

            </div>
          </div>
        <?php endforeach ?>
      </div>
    </div>
    <div class="col-md-12 mb-5 pb-3">
      <h3>Új épület tipus létrehozása</h3>
      <form action="/create-building-type" method="POST">
        <div class="form-group row">
          <label for="inputName" class="col-sm-2 col-form-label">Épület/helyszin</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputName" name="buildingType">
          </div>
        </div>
    <!--     <div class="form-group row">
          <label for="inputName" class="col-sm-2 col-form-label">Kategória Neve</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputName" name="categoryName">
          </div>
        </div>
        <div class="form-group row">
          <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
          <div class="col-sm-10">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="categoryDescription"></textarea>
          </div>
        </div> -->

        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Elküldés</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>