<section class="ftco-section">
    <div class="container">
        <div class="col-md-12 mb-5 pb-3">
            <h3>Új személy rögzítése</h3>
            <form action="/create-personal" method="POST">
                <div class="form-group row">
                    <label for="inputLastNameId" class="col-sm-2 col-form-label">Vezetéknév</label>
                    <div class="col-sm-10">
                    <select name="lastNameId" id="inputLastNameId" class="form-control">
                        <?php foreach($params['lastNames'] as $lastName) : ?>    
                        <option value="<?= $lastName['lastNameId'] ?>">
                                <?= $lastName['lastName']?>
                            </option>
                        <?php endforeach ?> 
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputFirstNameId" class="col-sm-2 col-form-label">Keresztnév</label>
                    <div class="col-sm-10">
                    <select name="firstNameId" id="inputFirstNameId" class="form-control">
                        <?php foreach($params['firstNames'] as $firstName) : ?>    
                        <option value="<?= $firstName['firstNameId'] ?>">
                                <?= $firstName['firstName']?>
                            </option>
                        <?php endforeach ?> 
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputPostId" class="col-sm-2 col-form-label">Pozíció</label>
                    <div class="col-sm-10">
                    <select name="postId" id="inputPostId" class="form-control">
                        <?php foreach($params['posts'] as $post) : ?>    
                        <option value="<?= $post['postId'] ?>">
                                <?= $post['post']?>
                            </option>
                        <?php endforeach ?> 
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputTitleId" class="col-sm-2 col-form-label">Titulus</label>
                    <div class="col-sm-10">
                        <select name="titleId" id="inputTitleId" class="form-control">
                        <?php foreach($params['titles'] as $title) : ?>    
                        <option value="<?= $title['titleId'] ?>">
                                <?= $title['title']?>
                            </option>
                        <?php endforeach ?> 
                        </select>
                    </div>
                </div>
             <!--    <div class="form-group row">
                    <div class="col-sm-2">Aktív</div>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck1" name="isActive">
                        </div>
                    </div>
                </div> -->
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Elküldés</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>