<section class="ftco-section">
    <div class="container">
        <div class="col-md-12 mb-3 pb-3">
            <h3><?= $params['buildingType']['buildingType']?></h3>
            <form action="/update-buildingType/<?= $params['buildingType']['buildingTypeId']?>" method="POST">
                <div class="form-group row">
                    <label for="inputName" class="col-sm-2 col-form-label">Név</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" name="name" value="<?=$params['buildingType']['buildingType']?>">
                    </div>
                </div>
             
                <!-- <div class="form-group row">
                    <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"><?= $params['buildingTypes']['buildingTypeDesc'] ?></textarea>
                    </div>
                </div> -->

               

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Elküldés</button>
                    </div>
                    <!-- <form action="/delete-dish/<?= $dish['id']?>" method="POST" class="d-inline-block">
                <button class="btn btn-sm btn-outline-danger" >Törlés</button>
              </form> -->
                </div>
            </form>
        </div>
    </div>
</section>