
  <div class=" container">
    <div class="col-md-12  pb-3">
      <div class="p-4 mb-4 rounded-3">
        <div>
          <h1 class="display-5 fw-bold text-danger text-center">Felhasználói adatok</h1>
          <p class="text-center lead">Módosítsa amennyiben nem találja helyesnek!</p>
        </div>
      </div>
      <div class="">
        <?php if (isset($params['isSuccess'])) : ?>
          <div class="alert alert-success text-center ">
            <p class="">Sikeres</p>
          </div>
        <?php endif; ?>
      </div>
    </div>

    <form action="/new-employee" method="POST" class="">
      <div class="form-group row">
        <label for="inputTitleId" class="col-sm-2 col-form-label">Titulus</label>
        <div class="col-sm-10">
          <select name="titleId" id="inputTitleId" class="form-control">
            <?php foreach ($params['titles'] as $title) : ?>
              <option class=" text-dark" value="<?= $title['titleId'] ?>">
                <?= $title['title'] ?>
              </option>
            <?php endforeach ?>
          </select>
        </div>
      </div>
      <div class="form-group row mt-5 ">
        <label for="lastname" class="col-sm-2 col-form-label">Vezetéknév:</label>
        <div class="col-sm-10">
          <input type="text" name="lastname" class="form-control " placeholder="vezetékneve?" />
          <div class="invalid-feedback">
            <p>üzi</p>
          </div>
        </div>
      </div>
      <div class="form-group row mt-5">
        <label for="inputFirstNameId" class="col-sm-2 col-form-label">Keresztnév</label>
        <div class="col-sm-10">
          <select name="firstNameId" id="inputFirstNameId" class="form-control">
            <?php foreach ($params['firstNames'] as $firstName) : ?>
              <option class=" text-dark" value="<?= $firstName['firstNameId'] ?>">
                <?= $firstName['firstName'] ?>
              </option>
            <?php endforeach ?>
          </select>
        </div>
      </div>

      <div class="form-group row mt-5  ">
        <label for="birtday" class="col-sm-2 col-form-label">Születési dátum:</label>
        <div class="col-sm-10">
          <input type="datetime-local" name="birtday" class=" form-control" placeholder="Született" />
          <div class="invalid-feedback">
          </div>
        </div>
      </div>
      <div class="form-group row mt-5">
        <label for="inputPostId" class="col-sm-2 col-form-label">Pozíció</label>
        <div class="col-sm-10">
          <select name="postId" id="inputPostId" class="form-control">
            <?php foreach ($params['posts'] as $post) : ?>
              <option class=" text-dark" value="<?= $post['postId'] ?>">
                <?= $post['post'] ?>
              </option>
            <?php endforeach ?>
          </select>
        </div>
      </div>
      <div class="form-group row mt-5">
        <label for="otherInfo" class="col-sm-2 col-form-label">Egyéb információ</label>
        <div class="col-sm-10">
          <textarea class="form-control" id="otherInfoId" name="otherInfo" rows="3"></textarea>
        </div>
      </div>
      <div class="form-check row m-5">
        <label for="isVerifed" class=" col-sm-4 col-form-label">Elfogadom a felhasználói feltételeket</label>
        <input class="" type="checkbox" name="isVerified" />
        <div class="invalid-feedback">
        </div>
      </div>

      <div class="m-2">
        <button class="btn btn-primary" type="submit">Küldés</button>
      </div>
    </form>
  </div>

  
