<?php
//  echo "<pre>";
// var_dump($params['errorMessages']);

$isValidClass = function ($key) use ($params) {
    if (!$params['errorMessages']) {
        return "";
    }
    return count($params['errorMessages'][$key] ?? []) ? "is-invalid" : "is-valid";
};
?>
<section class="ftco-section pt-3">
    <div class="container">
        <div class="col-md-12 mb-5 pb-3">
            <h3>Bejelentkezés</h3>
            <?php if ($params['isSuccess']) : ?>
                <div class="alert alert-success text-center m-2">
                    <i class="fa fa-check-circle display-1"> </i>
                </div>
            <?php endif; ?>
            <form action="/login" method="POST" class="">
                <div class="form-group-row">

                    <label for="email" class="col-sm-2 col-form-label">Email</label>

                    <input type="email" class="form-control <?= $isValidClass('email') ?>" id="email" name="email">

                    <div class="invalid-feedback">

                        <?php foreach ($params['errorMessages']['email'] as $error) : ?>
                            <?= $error ?> <br />
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="form-group-row">
                    <label for="password" class="col-sm-2 col-form-label">Jelszó</label>

                    <input type="password" class="form-control <?= $isValidClass('email') ?>" id="password" name="password">

                    <div class="invalid-feedback">
                        <?php foreach ($params['errorMessages']['password'] as $error) : ?>
                            <?= $error ?> <br />
                        <?php endforeach; ?>
                    </div>
                </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Küldés</button>
            </div>
        </div>
        </form>
        <div>
            <a class="float-right text-danger"href="">Regisztrációhoz kattintson ide!</a>
        </div>
    </div>
    </div>
</section>