<section class="ftco-section">
    <div class="container">
    <p>
            <?php echo 
    $_SESSION['userId'];
    ?>
            </p>
        <div class="row">
      
    
            <?php foreach ($params['dishTypesWithDishes'] as $dishType): ?>
            <div class="col-md-6 mb-5 pb-3">
                <h3 class="mb-5 heading-pricing ftco-animate fadeInUp ftco-animated text-warning">
                    <?= $dishType['name'] ?>
                </h3>

                <?php foreach($dishType['dishes'] as $dish):?>
                <div class="pricing-entry d-flex ftco-animate fadeInUp ftco-animated">
                    <div class="desc pl-3">
                        <div class="d-flex text align-items-center">
                            <h3>
                                <span>
                                    <?= $dish['name']?>
                                </span>
                            </h3>
                            <span class="price">  <?= $dish['price']?></span>
                        </div>
                        <div class="d-block">
                            <p>
                            <?= $dish['description']?> </p>
                        </div>
                    </div>
                </div>
                    <?php endforeach ?>
            </div>
            <?php endforeach ?>
        </div>
    </div>
</section>