<section class="ftco-section pt-3">
    <div class="container">

        <div class="col-md-12 mb-5 pb-3">
            <div class="jumbotron text-center ">
                <h2 class="text-success">A taralom megtekintéséhez bejelentkezés szükséges</h2>

            </div>
        </div>
        <form action="/register" method="POST">
            <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="email" name="email">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Jelszó</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-success">Regisztráció</button>
                </div>
            </div>
        </form>
    </div>
</section>