<?php
//  echo "<pre>";
// var_dump($params['errorMessages']);

$isValidClass = function ($key) use ($params) {
    if (!$params['errorMessages']) {
        return "";
    }
    return count($params['errorMessages'][$key] ?? []) ? "is-invalid" : "is-valid";
};
?>
<section class="ftco-section">
    <div class="container">

        <div class="col-md-12">
            <div class="jumbotron text-center ">
                <h2 class="text-success">Regisztráció után bejelentkezhet!</h2>
                <h2><? if($params['info']):?>
                       
                       <p class="text-danger"><? echo $params['info']?></p>
                       
                       <?php endif;?></h2>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="col-md-12 mb-5 pb-3">
            <h3>Regisztráció</h3>
            <?php if ($params['isSuccess']) : ?>
                <div class="alert alert-success text-center m-2">
                    <i class="fa fa-check-circle display-1"> </i>
                </div>
            <?php endif; ?>
            <form action="/register" method="POST">
                <div class="form-group-row">

                    <label for="email" class="col-sm-2 col-form-label">Email</label>

                    <input type="email" class="form-control <?= $isValidClass('email') ?>" id="email" name="email" value="<?=$params['values']['email'] ?? ''?>">

                    <div class="invalid-feedback">

                        <?php foreach ($params['errorMessages']['email'] as $error) : ?>
                            <?= $error ?> <br />
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="form-group-row">
                    <label for="password" class="col-sm-2 col-form-label">Jelszó</label>

                    <input type="password" class="form-control <?= $isValidClass('password') ?>" id="password" name="password"value="<?=$params['values']['password'] ?? ''?>">

                    <div class="invalid-feedback">
                        <?php foreach ($params['errorMessages']['password'] as $error) : ?>
                            <?= $error ?> <br />
                        <?php endforeach; ?>
                    </div>
                </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Regisztráció</button>
            </div>
        </div>
        </form>
    </div>
    </div>
</section>